version: '3.8'
services:
  usuario-service:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources/wallet:/app/wallet:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    