version: '3.8'
services:
  usuario-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/wallet:/app/wallet:ro
    environment:
      - SPRÃ‡ING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    